---

- name: Set default trust policy for new certificates
  debconf:
    name: 'ca-certificates'
    question: 'ca-certificates/trust_new_crts'
    vtype: 'select'
    value: '{{ "yes" if (boss__pki__system_ca_certificates_trust_new | bool) else "no" }}'

- name: Get list of known certificates
  shell: grep -E -e '^[^#].*$' /etc/ca-certificates.conf | sed -e 's/^!//'
  register: boss__pki__register_ca_certificates_known
  changed_when: False

- name: Get list of untrusted certificates
  shell: grep -E -e '^!+' /etc/ca-certificates.conf | sed -e 's/^!//'
  register: boss__pki__register_ca_certificates_untrusted
  changed_when: False

- name: Get list of trusted certificates
  shell: grep -E -e '^[^#!].*$' /etc/ca-certificates.conf | sed -e 's/^!//'
  register: boss__pki__register_ca_certificates_trusted
  changed_when: False

- name: Get list of blacklisted certificates
  shell: grep -E -e '{{ boss__pki__system_ca_certificates_blacklist | join("' -e '") }}' /etc/ca-certificates.conf | sed -e 's/^!//'
  register: boss__pki__register_ca_certificates_blacklist
  changed_when: False
  when: boss__pki__system_ca_certificates_blacklist is defined and boss__pki__system_ca_certificates_blacklist

- name: Get list of whitelisted certificates
  shell: grep -E -e '{{ boss__pki__system_ca_certificates_whitelist | join("' -e '") }}' /etc/ca-certificates.conf | sed -e 's/^!//'
  register: boss__pki__register_ca_certificates_whitelist
  changed_when: False
  when: boss__pki__system_ca_certificates_whitelist is defined and boss__pki__system_ca_certificates_whitelist

- name: Configure system CA certificates
  template:
    src: 'etc/ca-certificates.conf.j2'
    dest: '/etc/ca-certificates.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Reconfigure ca-certificates' ]
