---
- name: Converge
  hosts: all
  become: yes
  become_method: sudo
  environment:
    SHELL: /bin/bash
  roles:
    - role: boss-ansible-role-core
    - role: boss-ansible-role-fact
    - role: boss-ansible-role-environment

    # FIXME: Figure out proper way to test this
    # - role: boss-ansible-role-pki
    #   bossjones__user: root
    #   bossjones__group: root


